module.exports = {
    CUSTOMERS: "WHO ARE YOUR CUSTOMERS?",
    SPECIAL_REQUIREMENTS: "ARE THERE ANY SPECIAL REQUIREMENTS LIKE TECHNOLOGY, LOCATION, ETC?",
    CUSTOMERS_EXCLUDED: "WHAT TYPES OF CUSTOMERS SHOULD BE EXCLUDED?",
    POSITIONS: "WHAT ARE THE POSITIONS OF YOUR PROSPECTS?",
};